# Generated by Django 5.2.6 on 2025-09-26 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('copropietarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50)),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('CASA', 'CASA'), ('DEPARTAMENTO', 'DEPARTAMENTO')], max_length=20)),
                ('torre', models.CharField(blank=True, max_length=100, null=True)),
                ('bloque', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('copropietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='copropietarios.copropietario')),
            ],
            options={
                'db_table': 'casa',
                'constraints': [models.UniqueConstraint(fields=('tipo', 'torre', 'bloque', 'piso', 'numero', 'copropietario'), name='uq_unidad_por_propietario_y_ubicacion')],
            },
        ),
    ]
