# Generated by Django 5.2.6 on 2025-09-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Copropietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('carnet', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('usuario', models.CharField(editable=False, max_length=150, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'copropietario',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
