# Generated by Django 5.2.6 on 2025-09-27 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('foto', models.TextField(blank=True, null=True)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='casas.casa')),
            ],
            options={
                'db_table': 'mascota',
                'indexes': [models.Index(fields=['casa'], name='mascota_casa_id_7634ca_idx'), models.Index(fields=['nombre'], name='mascota_nombre_a88f58_idx')],
            },
        ),
    ]
