# Generated by Django 5.2.6 on 2025-09-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('carnet', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('usuario', models.CharField(editable=False, max_length=150, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('turno', models.CharField(choices=[('DIA', 'Día'), ('NOCHE', 'Noche'), ('ROTATIVO', 'Rotativo')], default='ROTATIVO', max_length=10)),
                ('empresa', models.CharField(blank=True, max_length=120)),
                ('puesto', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'guardia',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
