# Generated by Django 5.2.6 on 2025-09-25 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('copropietarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('fechaIngreso', models.DateField()),
                ('fechaSalida', models.DateField(blank=True, null=True)),
                ('horaIngreso', models.TimeField()),
                ('horaSalida', models.TimeField(blank=True, null=True)),
                ('placa', models.CharField(blank=True, max_length=20)),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'pendiente'), (1, 'ingreso'), (2, 'salio')], default=0)),
                ('foto1_b64', models.TextField()),
                ('foto2_b64', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copropietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitantes', to='copropietarios.copropietario')),
            ],
            options={
                'db_table': 'visitante',
                'ordering': ['-created_at'],
            },
        ),
    ]
