# Generated by Django 5.2.6 on 2025-09-27 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=20)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='casas.casa')),
            ],
            options={
                'db_table': 'vehiculo',
                'indexes': [models.Index(fields=['placa'], name='vehiculo_placa_739f6c_idx'), models.Index(fields=['casa'], name='vehiculo_casa_id_bbc662_idx')],
                'constraints': [models.UniqueConstraint(fields=('placa', 'casa'), name='uq_placa_por_casa')],
            },
        ),
    ]
